//insert data in table using queries with sql server
import java.sql.*;
import java.io.*;
public class InsertData {


	public static void main(String[] args) {
		
	Connection con=null;//interface to conect with data
	Statement st=null;//interface to execute queries on table
	//ResultSet rs=null;//interface to read data from table
	try{
	Class.forName("com.mysql.jdbc.Driver");
	con=DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","");
	}
	catch (ClassNotFoundException e){
		System.out.println("Invalid Driver" +e.getMessage());
		System.exit(0);
		
	}
	catch (SQLException e){
		System.out.println("Invalid Dsn" +e.getMessage());
		System.exit(0);
		
		
	}
try{
	//initialize statement to execute queries
	st=con.createStatement();
	BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
	String name=null;
	String dob=null;
	int y=0;
	double salary=0;
//	int id=0;
	String sex=null;

//	System.out.println("enter id:");
//	id=Integer.parseInt(br.readLine());
	//if id is generated by sql server then no need to enter id value from keyboard
	do{
		
		
	System.out.println("enter name:");
	name=br. readLine().toUpperCase().trim();
	System.out.println("enter date of birth (yyyy-mm-dd):");
	dob=br.readLine();
	System.out.println("enter salary:");
	salary=Double.parseDouble(br.readLine());
	do{
		
		System.out.println("enter gender (m/f):");
		sex=br.readLine().toUpperCase().trim();
		if(sex.length()>1)
			System.out.println("invalid gender");
			
		
	}while(sex.length()>1);
	//inset into emp(name,dob,saalry)values("abc","1/1/2000',5000)
	String qry="insert into emp values(0,'"+name+"','"+dob+"',"+salary+",'"+sex+"')";
	//System.out.print(qry)//to print qry on screen
	st.executeUpdate(qry); //for insert,update,delete
	System.out.println("1.want to enter more data:");
	System.out.println("2.exit");
	y=Integer.parseInt(br.readLine());
	
	}while(y==1);
}
catch (SQLException e){
	System.out.println("query error :"+ e.getMessage());
}
catch (IOException e){
	System.out.println("input error :"+ e.getMessage());
}
catch (NumberFormatException e){
	System.out.println("invalid numeric  error :"+ e.getMessage());
	
}
finally{
	try{
	//	st.close();
		con.close();
		
	}
	catch(SQLException e){
	
	}
	
}
}
	}




	

